# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: PR Title Check

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    branches: [main]
    # milestoned is added here so that a PR can be re-triggered if it is milestoned.
    types: [milestoned, opened, edited, synchronize]

jobs:
  run:
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@c12c3d15f2655420ae2be8da400daae0919f6f3d # v1.21.3
